const string SELECT_FUND_TOPIC = "SelectFund";
const string SELECT_FUND_TOPIC_ACK = "SelectFundAck";
const string DEPOSIT_TOPIC = "Deposit";
const string WITHDRAW_TOPIC = "Withdraw";
const string TRANSACTION_TOPIC = "Transaction";
const string FUND_DATA_TOPIC = "FundData";
const string MESSAGE_TOPIC = "Message";

// Funds types availables
enum FundType 
{
    SAVINGS, 
    HOUSING
};

// Message types availables
enum MessageType
{
    SUCCESS, 
    FAILURE,
    WARNING
};

struct SelectFund
{
    @key	
    FundType fund_type;
};

struct SelectFundAck
{
    @key    
    FundType fund_type;
};

struct Deposit 
{
    int32 amount;
};

struct Withdraw 
{
    int32 amount;
};

struct Transaction 
{
    @key
    FundType fund_type_destination;
    int32 amount;
};

struct FundData 
{
    @key
    FundType fund_type;
    int32 amount;
};

//Topic
struct Message
{
    int64 date;
    MessageType message_type;
    sequence<int32> literals;
    sequence<string> data;
};


